version: '3'
services:
  mysqldb:
    image: mysql:8.0.36
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=3830-scripting-projeto-inicial_api
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - vollmed
  
  api:
    build: .
    container_name: 3830-scripting-projeto-inicial_api
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/3830-scripting-projeto-inicial_api?createDatabaseIfNotExist=true
    depends_on: 
      - mysqldb
    ports:
      - "8000:8080"
    networks:
      - 3830-scripting-projeto-inicial_api

networks:
  vollmed:
    driver: bridge

volumes:
  mysql-data:
